### ISSUE TITLE
Flush and/or redraw on non-tty output?

### ISSUE THREAD

**Issue by onyxraven** [jfelchner/ruby-progressbar#100]
I would love to use the ruby-progressbar output in a jenkins job.  As it stands now, that output is not customizable for non-tty, so this is a multi-part request.

1. allow non-tty customization (ok if it is a different config var)
2. allow for output 'redraw' on a new line on progress step
  * I imagine this looking something like:

    ```
    |=                   |
    |==                  |
    |===                 |
    ```

**Comment by jfelchner** [comment]
@onyxraven You have no idea how many people requested that non-TTY output NOT do that. :grinning: 

Output for non-tty cannot be customized for the reasons I gave in the README since (as I'm sure you're aware), the line cannot be removed and must go to the next line.

I had many requests that non-TTY output behave as it currently does because, say for example on Jenkins and Travis jobs, people were getting thousands of lines of log output, which isn't desirable.

Can I ask what your use case is for wanting to see all those lines every time the bar is refreshed?

It's possible that I can add in a `force_tty` option that you can pass in when the bar is created, but I don't want to add anything new unless there's a really good case for it.  (I understand that I'm sure you think your case is a good one :wink:).

Thanks for the report!

**Comment by onyxraven** [comment]
Maybe I've got it configured wrong?  We're still on rspec 2 so we're possibly behind a version.  

In my jenkins currently, it simply shows
```
Progress: |
```
until the very end of the job where it finally fills in the bar.

I was hoping for something more like wget does in non-tty, where it redraws the line for each new segment (but not every single update), so you just get the smaller number of updates to know something is happening.  It looks like jenkins, by default, wants to see a newline before it'll flush to the web browser.

As for configuration, I understand about the rewriting, but it seems like a simplified grammar to change the `=` to `.`, for example, with caveats that not everything will work.

**Comment by jfelchner** [comment]
@onyxraven Yep, that'd be the problem. :grinning:

Fuubar 2.0 (which I also maintain) is only RSpec 3.x compatible.  If you'd like to submit a PR to Fuubar off of the last 1.x commit to get it working with the latest version of `ruby-progressbar` I think that everything would work exactly like you're wanting it to.

Here's the relevant part of the README that I think you'd be interested in:

https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output

**Comment by onyxraven** [comment]
Gotcha.  I'll submit a PR to Fuubar. Shouldn't be too much to change.  Thanks for the quick responses, and awesome gems!
