### ISSUE TITLE
Fails to install with MediumSecurity due to expired cert

### ISSUE THREAD

**Issue by svoop** [jfelchner/ruby-progressbar#159]
Looks like the cert needs some love:

```
The gem ruby-progressbar-1.10.1 can't be installed because the security policy
didn't allow it, with the message: certificate
/CN=accounts_rubygems/DC=thekompanee/DC=com not valid after 2019-08-03 21:34:05
UTC
```

**Comment by jfelchner** [comment]
Thanks for the heads up!

**Comment by svoop** [comment]
Works now, thanks!

**Comment by jfelchner** [comment]
I didn't fix anything yet :)  Not sure what changed but I'm going to reopen to make sure it's working as expected.

**Comment by svoop** [comment]
You're right, apparently, `gem cert --add` doesn't bark when adding an already expired cert.

**Comment by svoop** [comment]
Still failing, however, you might want to track the work on an issue on Bundler which should make it a little easier to create the checksums. Still far from a real standardized approach, but something nonetheless. :smile:

https://github.com/rubygems/rubygems/issues/3386

**Comment by jfelchner** [comment]
@svoop thanks for circling back here.  I'm currently in the process of converting the gem over to Github Actions and will be doing all the cert updates and such.  It's not so much the checksums that are the problem, it's that the certs are only a year in duration.  For gems like ruby-progressbar that don't change much (if at all) because they're effectively feature complete, it's a maintenance pain.

**Comment by jfelchner** [comment]
@svoop sorry this took me freaking eight months to do. 🙄 The next release should be signed correctly and additionally the latest version of `gem` allows one to specify the length of the cert.  This one is signed for four years which should keep this from happening again.

https://github.com/jfelchner/ruby-progressbar/commit/f8d6f1b60887957525defe2db5b135c4b3a946b0

**Comment by svoop** [comment]
@jfelchner 

Cool, thanks!

> It's not so much the checksums that are the problem, it's that the certs are only a year in duration.

Totally, but wrenching up the duration is merely a workaround. I might take a look at the rubygems.org repo to see how difficult it would be to read the certs when a gem is upped and then remind the author say 1 month prior to expiration. Beyond this, the whole checksumming should really be more standardized to lift adoption rate – maybe you want to share your Github Actions? 

[Given recent events](https://en.wikipedia.org/wiki/2020_United_States_federal_government_data_breach) it feels awkward only so few gems are checksummed at all.

**Comment by jfelchner** [comment]
Oh, sorry, the signing happens locally.  I just meant that I was updating to Github Actions _and_ doing all my gem maintenance, which is why I was finally getting to this.

I personally believe that the [checksums](https://github.com/jfelchner/ruby-progressbar/tree/master/checksum) are a better automated process than the certs, but obviously that isn't built into Rubygems.

My script signs my gems as they are released and I wouldn't feel comfortable giving even Github access to my private key to sign them in an action.  All that would do is to make Github an even larger target than it already is.

I would say that if you can get Bundler to include effortless signing in its `release` subcommand, that'd be an excellent start.  I would suggest certs be stored in `${HOME}/.gem/certs` and have a configuration option that can change that which could be set in `.gemrc`.

**Comment by jfelchner** [comment]
@svoop version `1.11.0` has just been released.  This should resolve your issues.  Thank you for your patience.

**Comment by svoop** [comment]
@jfelchner Works like a charm now, thanks a bunch and Happy New Year!

**Comment by svoop** [comment]
@jfelchner ~~Works like a charm now, thanks a bunch and Happy New Year!~~

Oh, I was a little to quick here cheering after the first green line, there's still a problem it seems:

<img width="481" alt="Screen Shot 2020-12-31 at 10 09 11" src="https://user-images.githubusercontent.com/7255/103403426-4e6a7a80-4b50-11eb-81e8-7520d5dc0a5a.png">

Nonetheless of course, I wish you a Happy New Year!

**Comment by jfelchner** [comment]
@svoop all certs have to be manually trusted on your machine as per the instructions on the rubygems site.

I believe it is `gem cert --add <path-to-public-cert>` which is why I include it in the gem repo.

**Comment by svoop** [comment]
@jfelchner You're right, my bad, everything's fine:

> cert-27850f9c2a8cb74b52e23266716d2f206bf0d9973bc606b701a4d13591a4fa05.pem
issuer= /CN=accounts_rubygems/DC=thekompanee/DC=com
notAfter=Dec 26 22:31:16 2021 GMT
