### ISSUE TITLE
Optionally allow progress beyond the set total

### ISSUE THREAD

**Issue by benalavi** [jfelchner/ruby-progressbar#171]
Current Problem
--------------------------------------------------------------------------------

I typically use progressbar for long running shell tasks like importing or transforming lots of records. A lot of times I find myself writing these quickly, untested, and ad-hoc just to start working on solving some issue. It's pretty common (for me at least) for a bug somewhere to lead to accidentally incrementing the progress-bar past the total, which then immediately crashes my script if I'm using `progress +=`. This can be pretty frustrating if/when the script has been running for a while and I don't get to see what otherwise would've happened.

My use case for using `progress +=` (which is probably tied to the `total` being wrong 😅 ) is usually when I'm doing something multi-threaded in batches and want to increment the progress by the batch size but want to see the total number of records processed (rather than the total number of batches).

Using `increment` I get a warning which is nicer, but I think it would be nice to be able to ignore it entirely, especially when I'm off by a lot and have other output I care about.

I know I can set the total to `nil` as per https://github.com/jfelchner/ruby-progressbar/wiki/Unknown-Progress but I often have a pretty good idea of what the total was going to be, and it's still helpful to have an idea of the script's progress even if I'm ultimately wrong (especially if I'm wrong by 1).

I would find it useful if there was an option to allow the progress to go beyond the set total without warning/raising. For my use cases at least I would probably just always use the option. I don't think I ever want invalid progress to crash my script or warn me, which is what I think this old issue may have been getting at: https://github.com/jfelchner/ruby-progressbar/issues/133, though I can see the utility in uncovering a bug.

Potential Solution or New Behavior
--------------------------------------------------------------------------------

### Mockups

I imagine with the option enabled it could increment the total by the same amount as the increasing progress and the bar would just kind of hang at 100% while still counting up (IIRC I've seen this behavior before, maybe while installing Windows a long time ago...)

**Comment by jfelchner** [comment]
@benalavi there is a _lot_ of code that's tied to the progress being <= the total.  Many downstream assumptions we can make which don't cause us to have to check to see if `progress > total ? total : progress`

I definitely see your use case, however I feel that with both the unknown progress option as well as the fact that the user has the ability to both check and modify both the total and progress, this is something best done outside of the core progressbar code.  You specifically said here:

> especially when I'm off by a lot

I would argue if you don't really know what the total is and won't until you finish, it might not be a good use case for using a progressbar at all.  A simple counter may be all you need.

Otherwise I would say just increase the total once the bar gets to one less than the total.

```ruby
loop
  bar.total += 1 if bar.progress == bar.total - 1

  # stuff

  bar.progress += 1
end
```

Or whatever makes sense for your code.

Sorry for not being able to help here!
