### ISSUE TITLE
Support for FiraCode progressbar

### ISSUE THREAD

**Issue by krissi** [jfelchner/ruby-progressbar#178]
New Behavior
--------------------------------------------------------------------------------

The FiraCode font (https://github.com/tonsky/FiraCode) includes special glyphs for progressbars. In the current implementation the `|` at the beginning and end of the bar are not part of the progressbar itself, but in the format string. When using the glyphs from the FireCode font, the first char of the bar is part of the bar as well (U+EE00/U+EE03, see image below), the same for the last char.

I wonder if there is a way in the current implementation to fully use the code which I am missing and if not, if you are willing to accept PRs regarding this feature.

### FiraCode progressbars in a nutshell
![Glyphs](https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/progress.png)
![In action](https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/progress.gif)

**Comment by jfelchner** [comment]
I don't think this would be easily possible unfortunately.  Each progress mark needs to be the same thing.  I would much prefer to have seen FiraCode make the first mark a vertical line with padding on the righthand side of the glyph and the last mark padding followed by a vertical line on the lefthand side of the glyph so that each progress mark could be identical.

**Comment by jfelchner** [comment]
@krissi if you submit a PR to FiraCode, link it back here so we can track it.
