### ISSUE TITLE
Certificat expired

### ISSUE THREAD

**Issue by damienlethiec** [jfelchner/ruby-progressbar#183]
Hi there,

I am back to an old project that uses progress bar 1.11.0 and when I bundle install I get the following error:
`The gem ruby-progressbar-1.11.0 can't be installed because the security policy didn't allow it, with the message: certificate /CN=accounts_rubygems/DC=thekompanee/DC=com not valid
after 2021-12-26 22:31:16 UTC`

If I follow the steps here (https://github.com/jfelchner/ruby-progressbar/wiki/Installation#gem-signing) I still get blocked at the gem install steps with a wrong certificate.

Don't you need to update the certificate for the gem?

Thanks a ton,
Damien

**Comment by jfelchner** [comment]
@damienlethiec Yes.  I will be updating this next weekend.  I usually do this over the holiday but I got busy with various family things.  I'm actually surprised that the cert in the repo wan't updated last year.  I'm almost certain that I did.  Anyway, I will get to this for you.  My apologies.

**Comment by damienlethiec** [comment]
Thanks so much :)

**Comment by jfelchner** [comment]
@damienlethiec finally got this out!  I'm going to release `1.12` here in a bit and it will have [an updated cert](https://github.com/jfelchner/ruby-progressbar/commit/da119801092c36c7ba397c72c6252a3cf49c881f) which will now be valid for 3 years rather than 1 year.  Thank you for bringing this to my attention!
